### ISSUE TITLE
Latest update crashing during start

### ISSUE THREAD

**Issue by tim77** [flathub/io.github.tdesktop_x64.TDesktop#32]
```
8bb76701e802753b46b0f2d7da4035032954be85c3cf89ccaa2d841441f9ded8
Update Qt patches to desktop-app/patches@c80c0d5 (b2dde8e7)
2023-10-11 17:33:00 +0000
```
Doesn't work and crashing during app starting. Downgdrade to `eb61ec1d932f8004bb3a226e450e1de9bf5a79541894424b8ff9ff8abcff0b04` helps.

Sorry for lack of details, just a quick report for now.

**Comment by donorsemen** [comment]
I confirm that I have a similar problem and it too is only cured by rolling back to the previous version. Although the original telegram from flethub got the update at the same time as 64gram, but it works without problems. 
The terminal does not produce any reasonable logs even with the --verbose option. Arch Linux, gnome 45.

**Comment by tehcneko** [comment]
This should be fixed now(still building), but you can try this:
`flatpak install --user https://dl.flathub.org/build-repo/58757/io.github.tdesktop_x64.TDesktop.flatpakref`

**Comment by tim77** [comment]
Thanks, it works now!
