### ISSUE TITLE
Disable libdecor on Wayland if SSD is available

### ISSUE THREAD

**Issue by mochaaP** [flathub/io.github.tdesktop_x64.TDesktop#9]
AFAIK only Mutter doesn't have SSD support. However, when "use system window borders" is enabled, the window still renders a titlebar, but with libdecor instead of Qt (or https://wayland.app/protocols/xdg-decoration-unstable-v1 on supported compositors).

**Comment by tehcneko** [comment]
please report this to upstream: https://github.com/telegramdesktop/tdesktop/issues

**Comment by mochaaP** [comment]
This is not reproducible on the official AppImage release nor on a system build (linked against unpatched system libs). That's why I'm reporting the issue here.

**Comment by tehcneko** [comment]
> 

Flatpak build should behave the same as the static binary build

**Comment by tehcneko** [comment]
Have you tried official Telegram flatpak build?
